
server:
  port: 8080

app:
  datasource:
    main:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://192.168.0.254:5432/ecommerce
      username: postgres
      password: password
      pool-size: 30

spring:
  main:
    web-application-type: servlet
  mail:
    default-encoding: UTF-8
    host: smtp.office365.com
    username: pr.alimrad@outlook.com
    password: uuzrukuyfiedsnwm
    port: 587

encryption:
  salt:
    rounds: 10

jwt:
  algorithm:
    key: SpringJwtComplex
  issuer: ecommerce
  expiredInSeconds: 604800

